jerrychong25/awesome-malaysia

README.md

-Added Selangor sub section
-Added Sarawak sub section

Added Co-Working Space section

---

README.md

-Modified GDG Kuala Lumpur website
-Added Cyberjaya Starup Summit 2019, GDG DevFest Kuala Lumpur, Google I/O Extended Kuala Lumpur, TechLadies Kuala Lumpur Coding Weekend 2017 under Event section

Added Event section

---

README.md

-Added aCAT Penang under Startup section
-Added KualaLumpurJS under JavaScript section
-Added Ng-My 2019 and PyCon My 2019 under Event section

Added aCAT Penang, KualaLumpurJS, Ng-My 2019 and PyCon My 2019

---

README.md

-Added few co-working space location under Kuala Lumpur subsection

Added Co-Woring Space Kuala Lumpur subsection

---

README.md

-Added aCAT Penang under Penang subsection
-Fixed Co-working Space Kuala Lumpur subsection unable to navigate issue

Added Co-Working Space Penang subsection

---

README.md

-Added Banking & Finance subsection
-Added E Commerce subsection
-Added Logitstic subsection
-Added Payment subsection
-Added Weather subsection

Added Open API section

---

README.md

-Added Paypal, senangPay, Stripe under Payment subsection
-Removed API keywords for common use name in some subsections

Added more Payment examples under Open API section

---

README.md

-Added more co-working spaces DreamSpace Sunway Geo Avenue
-Added more co-working spaces in Sarawak

Added more co-working spaces

---

README.md

-Added KTMB MobTicket under Public Transportation subsection

Renamed Mobile App subsection from Logistic to Public Transporation

---

README.md

-Added LLM Traffic
-Added MYairports
-Modified KTM MyRailtime

Added more transport mobile apps

---

README.md

-Added myMOTAC under Mobile App Toursim subsesction

Added Mobile App Tourism subsection

---

README.md

-Added InforBenacaJKM
-Added K3M
-Added MCG Info
-Added MyIPU

Added Mobile App Environment subsection

---

README.md

Added Mobile App Legal subsection

---

README.md

Added Mobile App Taxation subsection

---

README.md

Renamed Mobile App subsection from Taxation to Finance

---

README.md

-Added e-Caruman
-Added i-Akaun

Added more finance mobile apps

---

README.md

Added Mobile App Economic Subsection

---

README.md

-Added Air Selangor
-Added Indah Water
-Added myTNB

Added Mobile App Utility subsection

---

README.md

Added Mobile App Housing subsection

---

README.md

-Added Communities Online (COOL)

Added Mobile App Community subsection

---

README.md

-Added GDEX
-Added POS Malaysia

Added Mobile App Logistic Subsection

---

README.md

-Added dahmakan
-Added Foodpanda
-Added Grab

Added Mobile App Food subsection

---

README.md

-Added Azure Community Malaysia (ACM)

Added Community By Platforms Azure subsection

---

.github/workflows/main.yml

Added Github Actions file

---

README.md

-Used Awesome official badge - https://awesome.re/badge.svg

Fixed Awesome badge

---

README.md

-Changed from Touch ‘n Go eWallet to TnG eWallet

Modified TnG eWallet name

---

README.md

-Fixed List item link and description must be separated with a dash

Fixed Co-Working Space Bersama-sama missing dash issue

---

README.md

Source: https://2021.pycon.my/

Added PyCon MY 2021 in Event Section

---

README.md

Adding Ethereum Kuala Lumpur to the list for devs into blockchain programming such as Solidity

Added ETHKL
